### ISSUE TITLE
Some results contain duplicates

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-classifier#11]
Executed the tool for "עקדת יצחק" and in the results I see some duplicates:
- jbr:text-tanach-13-7-31 appears twice.
- jbr:text-tanach-11-3-27 appears twice.

**Comment by NetanelFelcher** [comment]
It means that this source appears twice in the Wikipedia entry. We can easily remove duplicates using set instead of list, but I'm not sure this is the right thing to do 
@omishali

**Comment by omishali** [comment]
I checked and I didn't see that this source appears twice (at least not the
one from Yirmia).

2018-03-27 11:44 GMT+03:00 Netanel Felcher <notifications@github.com>:

**Comment by omishali** [comment]
OK, you may close the issue if that's the case.

בתאריך 7 באפר׳ 2018 7:19 אחה״צ,‏ "avnerec" <notifications@github.com> כתב:
